### ISSUE TITLE
deploy checklist

### ISSUE THREAD

**Issue by luke-h1** [luke-h1/airbnb-clone#355]
- [x] Limit prod SQL queries to properties created by logged in user (can't see other people's properties) 
- [x] Add yup validation to forms
- [x] check that inputs don't accept negative values
- [x] get rid of unused dependencies 
- [x] get rid of chakra ui components
- [x] move to argon2
- [x] Setup health check endpoint
- [x] manual test & ensure no bugs are left in api

**Comment by luke-h1** [comment]
API deployed
